### ISSUE TITLE
added options.

### ISSUE THREAD

**Issue by jamiemc71** [i3ucky/bucky_mdt#1]
hey would it be possible to add a discord webhook to push police reports to a discord chat? this would be a very handy option to have and reduce the work load on reports

**Comment by i3ucky** [comment]
hi, I will see what I can do

**Comment by flamespinner** [comment]
I submitted a pull request ( #4 ) with code that I have been using in my county to do New Note Creation and New Report Creation Webhooks for your consideration

**Comment by jamiemc71** [comment]
> I submitted a pull request ( #4 ) with code that I have been using in my county to do New Note Creation and New Report Creation Webhooks for your consideration

having an issue with this new feature getting the following error

[    script:bucky_mdt] SCRIPT ERROR: @bucky_mdt/sv_mdt.lua:221: attempt to index a nil value (global 'Vorpcore')
[    script:bucky_mdt] > rawQuery (@oxmysql/dist/build.js:25056)
[    script:bucky_mdt] > runMicrotasks (<anonymous>:0)
[    script:bucky_mdt] > processTicksAndRejections (node:internal/process/task_queues:96)

**Comment by i3ucky** [comment]
try now
